### ISSUE TITLE
type EventType string prevents dynamic event names

### ISSUE THREAD

**Issue by svenwiltink** [vansante/go-event-emitter#1]
I am trying to throw events, but I don't really control the names of the event. Because of this I run into the following error:

```
music\provider\mpv\mpv.go:97:39: cannot use event.Name (type string) as type eventemitter.EventType
```

This is a bit lame because the type of event.Name is string. I can't cast it to EventType either because string is a language struct and not an interface.

**Comment by vansante** [comment]
Yes, I changed the code so you have to define your events prior to emitting
them. You have to define all your events in a variable with the EventType
so you can't just emit events and listeners will be able to see the
EventTypes to listen to.

**Comment by svenwiltink** [comment]
that forces me to make these kind of functions though: 

```
func (mpvPlayer *MpvPlayer) getEmitterEventType(mpvEvent *mpvipc.Event) eventemitter.EventType {
	switch mpvEvent.Name {
	case "file-loaded":
		return "file-loaded"
	case "end-file":
		return "end-file"
	}

	return ""
}
```

**Comment by svenwiltink** [comment]
You can't do that: 
```
invalid case EventFileLoaded in switch on mpvEvent.Name (mismatched types eventemitter.EventType and string)
```

You have to define the constants as strings, which kind of defeats the purpose of the EventType type.

**Comment by svenwiltink** [comment]
It only makes the code uglier because you can't cast it to a string or cast a string to EventType. The code now looks like this, which is far from ideal:

```
   const (
	EventFileLoaded eventemitter.EventType = "file-loaded"
	EventFileEnded  eventemitter.EventType = "end-file"
    )
    -----------------------
    switch mpvEvent.Name {
	case "file-loaded":
		return EventFileLoaded
	case "end-file":
		return EventFileEnded
	}

	return ""
```

imo it should be up to the programmer to define constants for the event names
